import React from 'react'
import { Routes, Route } from 'react-router-dom'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Home from './pages/Home'
import About from './pages/About'
import Projects from './pages/Projects'
import Publications from './pages/Publications'
import Team from './pages/Team'
import Gallery from './pages/Gallery'
import Login from './pages/Login'
import AdminPanel from './pages/AdminPanel'
export default function App(){return (<div className='min-h-screen flex flex-col'><Navbar/><main className='flex-1'><Routes><Route path='/' element={<Home/>} /><Route path='/about' element={<About/>} /><Route path='/projects' element={<Projects/>} /><Route path='/publications' element={<Publications/>} /><Route path='/team' element={<Team/>} /><Route path='/gallery' element={<Gallery/>} /><Route path='/login' element={<Login/>} /><Route path='/admin' element={<AdminPanel/>} /></Routes></main><Footer/></div>)}
